[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.setuptools']

[phases.install]
cmds = [
    'python -m pip install --upgrade pip setuptools wheel',
    'python -m pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput',
    'python manage.py migrate --noinput'
]

[start]
cmd = 'gunicorn IntelliFace.wsgi:application --bind 0.0.0.0:$PORT --workers 2'